=== rekabaffi/F4IIYA_XMLGyak/XMLTaskF4IIYA/1.feladat/XMLSchemaF4IIYA.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!--Egyszerű elemek-->

    <xs:element name="cim" type="xs:string" />
    <xs:element name="hossz" type="hosszTipus" />
    <xs:element name="mufaj" type="mufajTipus" />
    <xs:element name="eloado" type="xs:string" />

    <xs:element name="nev" type="xs:string" />
    <xs:element name="terulet" type="xs:string" />
    <xs:element name="befogadokepesseg" type="xs:int" />
    <xs:element name="iranyitoszam" type="xs:int" />
    <xs:element name="varos" type="xs:string" />
    <xs:element name="utca_hazszam" type="xs:string" />

    <xs:element name="t_mufaj" type="xs:string" />

    <xs:element name="tagok_szama" type="xs:int" />
    <xs:element name="egyesulet" type="xs:string" />
    <xs:element name="korcsoport" type="xs:string" />

    <xs:element name="eletkor" type="xs:int" />
    <xs:element name="szuletesi_datum" type="idoTipus" />

    <xs:element name="pontszam" type="xs:int" />

    <!--Saját típusok-->

    <xs:simpleType name="mufajTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Pop" />
            <xs:enumeration value="Rock" />
            <xs:enumeration value="Elektronikus" />
            <xs:enumeration value="Romantikus" />
            <xs:enumeration value="Disco" />
            <xs:enumeration value="Jazz" />
            <xs:enumeration value="Country" />
            <xs:enumeration value="Hip-hop" />
            <xs:enumeration value="Rap" />
            <xs:enumeration value="Klasszikus" />
            <xs:enumeration value="Folk" />
            <xs:enumeration value="R and B " />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="hosszTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]:[0-9][0-9]" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idoTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="([12]\d{3}.(0[1-9]|1[0-2]).(0[1-9]|[12]\d|3[01]))" />
        </xs:restriction>
    </xs:simpleType>

    <!--Felépítés-->

    <xs:element name="F4IIYA_Tancverseny">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="zene" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="cim" />
                            <xs:element ref="hossz" />
                            <xs:element ref="mufaj" />
                            <xs:element ref="eloado" />
                        </xs:sequence>
                        <xs:attribute name="zene_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="versenyhelyszin" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="nev" />
                            <xs:element ref="terulet" />
                            <xs:element ref="befogadokepesseg" />
                            <xs:element name="cim" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="iranyitoszam" />
                                        <xs:element ref="varos" />
                                        <xs:element ref="utca_hazszam" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element> 
                        </xs:sequence>
                        <xs:attribute name="verseny_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="tanc" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="t_mufaj"/>
                            <xs:element ref="nev" />
                            <xs:element ref="hossz" />
                        </xs:sequence>
                        <xs:attribute name="tanc_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="csoport" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="tagok_szama" />
                            <xs:element ref="nev" />
                            <xs:element ref="egyesulet" />
                            <xs:element ref="korcsoport" minOccurs="1" maxOccurs="unbounded" />
                        </xs:sequence>
                        <xs:attribute name="csoport_id" type="xs:int" />
                        <xs:attribute name="produkcio" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="versenyzo" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="eletkor" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element ref="nev" />
                            <xs:element ref="szuletesi_datum" />
                            <xs:element name="lakcim" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="iranyitoszam" />
                                        <xs:element ref="varos" />
                                        <xs:element ref="utca_hazszam" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element> 
                        </xs:sequence>
                        <xs:attribute name="versenyzo_id" type="xs:int" />
                        <xs:attribute name="tag" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="tanc_helye" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="pontszam" />
                        </xs:sequence>
                        <xs:attribute name="th_id" type="xs:int" />
                        <xs:attribute name="tanc_id" type="xs:int" />
                        <xs:attribute name="verseny_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="lejatszott_zene" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="tanc_id" type="xs:int" />
                        <xs:attribute name="zene_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

        <!--Kulcsok-->

        <xs:key name="zene_kulcs">
            <xs:selector xpath="zene" />
            <xs:field xpath="@zene_id" />
        </xs:key>

        <xs:key name="helyszin_kulcs">
            <xs:selector xpath="versenyhelyszin" />
            <xs:field xpath="@verseny_id" />
        </xs:key>

        <xs:key name="tanc_kulcs">
            <xs:selector xpath="tanc" />
            <xs:field xpath="@tanc_id" />
        </xs:key>

        <xs:key name="csoport_kulcs">
            <xs:selector xpath="csoport" />
            <xs:field xpath="@csoport_id" />
        </xs:key>

        <xs:key name="versenyzo_kulcs">
            <xs:selector xpath="versenyzo" />
            <xs:field xpath="@versenyzo_id" />
        </xs:key>

        <xs:key name="tanc_helye_kulcs">
            <xs:selector xpath="tanc_helye" />
            <xs:field xpath="@th_id" />
        </xs:key>

        <!--Idegen kulcsok-->

        <xs:keyref refer="tanc_kulcs" name="tanc_idegen_kulcs">
            <xs:selector xpath="csoport" />
            <xs:field xpath="@produkcio" />
        </xs:keyref>

        <xs:keyref refer="csoport_kulcs" name="csoport_idegen_kulcs">
            <xs:selector xpath="versenyzo" />
            <xs:field xpath="@tag" />
        </xs:keyref>

        <xs:keyref refer="tanc_kulcs" name="tanc_tanchelye_idegen_kulcs">
            <xs:selector xpath="tanc_helye" />
            <xs:field xpath="@tanc_id" />
        </xs:keyref>

        <xs:keyref refer="helyszin_kulcs" name="verseny_tanchelye_idegen_kulcs">
            <xs:selector xpath="tanc_helye" />
            <xs:field xpath="@verseny_id" />
        </xs:keyref>

        <xs:keyref refer="tanc_kulcs" name="tanc_lejatszottzene_idegen_kulcs">
            <xs:selector xpath="lejatszott_zene" />
            <xs:field xpath="@tanc_id" />
        </xs:keyref>

        <xs:keyref refer="zene_kulcs" name="zene_lejatszottzene_idegen_kulcs">
            <xs:selector xpath="lejatszott_zene" />
            <xs:field xpath="@zene_id" />
        </xs:keyref>

        <!--1:1-->

        <xs:unique name="unique_tanc">
            <xs:selector xpath="csoport" />
            <xs:field xpath="@produkcio" />
        </xs:unique>

    </xs:element>

</xs:schema>

=== rekabaffi/F4IIYA_XMLGyak/XMLTaskF4IIYA/2.feladat/DOMParseF4IIYA/src/hu/domparse/f4iiya/XMLF4IIYA.xml
<?xml version="1.0" encoding="UTF-8"?>

<F4IIYA_Tancverseny xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaF4IIYA.xsd">

    <!--Zenék-->

    <zene zene_id="1">
        <cim>Ébredj fel</cim>
        <hossz>3:45</hossz>
        <mufaj>Pop</mufaj>
        <eloado>Kovács Anna</eloado>
    </zene>

    <zene zene_id="2">
        <cim>Korallpart</cim>
        <hossz>4:20</hossz>
        <mufaj>Rock</mufaj>
        <eloado>Szabó Bence és a Hangok</eloado>
    </zene>

    <zene zene_id="3">
        <cim>Táncolj!</cim>
        <hossz>2:58</hossz>
        <mufaj>Elektronikus</mufaj>
        <eloado>Electro Vibes</eloado>
    </zene>

    <zene zene_id="4">
        <cim>Szerelmi történet</cim>
        <hossz>5:12</hossz>
        <mufaj>Romantikus</mufaj>
        <eloado>Nagy Eszter és a Szívhangok</eloado>
    </zene>

    <zene zene_id="5">
        <cim>Éjszakai láz</cim>
        <hossz>3:30</hossz>
        <mufaj>Disco</mufaj>
        <eloado>DiscoFever Band</eloado>
    </zene>
    
    <!--Versenyhelyszínek-->

    <versenyhelyszin verseny_id="1">
        <nev>Park Stadion</nev>
        <terulet>800 négyzetméter</terulet>
        <befogadokepesseg>5000</befogadokepesseg>
        <cim>
            <iranyitoszam>1024</iranyitoszam>
            <varos>Budapest</varos>
            <utca_hazszam>Kossuth utca 10</utca_hazszam>
        </cim>
    </versenyhelyszin>

    <versenyhelyszin verseny_id="2">
        <nev>Sportaréna</nev>
        <terulet>1200 négyzetméter</terulet>
        <befogadokepesseg>10000</befogadokepesseg>
        <cim>
            <iranyitoszam>1132</iranyitoszam>
            <varos>Budapest</varos>
            <utca_hazszam>Rákospatak utca 5</utca_hazszam>
        </cim>
    </versenyhelyszin>

    <versenyhelyszin verseny_id="3">
        <nev>Sportközpont</nev>
        <terulet>600 négyzetméter</terulet>
        <befogadokepesseg>3000</befogadokepesseg>
        <cim>
            <iranyitoszam>3521</iranyitoszam>
            <varos>Debrecen</varos>
            <utca_hazszam>Sport utca 8</utca_hazszam>
        </cim>
    </versenyhelyszin>

    <versenyhelyszin verseny_id="4">
        <nev>Városi Stadion</nev>
        <terulet>1000 négyzetméter</terulet>
        <befogadokepesseg>7000</befogadokepesseg>
        <cim>
            <iranyitoszam>4023</iranyitoszam>
            <varos>Debrecen</varos>
            <utca_hazszam>Sport tér 15</utca_hazszam>
        </cim>
    </versenyhelyszin>

    <versenyhelyszin verseny_id="5">
        <nev>Park Stadion</nev>
        <terulet>850 négyzetméter</terulet>
        <befogadokepesseg>5500</befogadokepesseg>
        <cim>
            <iranyitoszam>1015</iranyitoszam>
            <varos>Budapest</varos>
            <utca_hazszam>Sport út 20</utca_hazszam>
        </cim>
    </versenyhelyszin>

    <!--Táncok-->

    <tanc tanc_id="1">
        <t_mufaj>Modern tánc</t_mufaj>
        <nev>Fények játéka</nev>
        <hossz>4:30</hossz>
    </tanc>

    <tanc tanc_id="2">
        <t_mufaj>Latin tánc</t_mufaj>
        <nev>Forró ritmusok</nev>
        <hossz>3:15</hossz>
    </tanc>

    <tanc tanc_id="3">
        <t_mufaj>Balett</t_mufaj>
        <nev>Hamupipőke álom</nev>
        <hossz>5:00</hossz>
    </tanc>

    <tanc tanc_id="4">
        <t_mufaj>Jazz tánc</t_mufaj>
        <nev>Éjszakai szimfónia</nev>
        <hossz>3:45</hossz>
    </tanc>

    <tanc tanc_id="5">
        <t_mufaj>Flamenco</t_mufaj>
        <nev>Tűz és szenvedély</nev>
        <hossz>4:20</hossz>
    </tanc>    

    <!--Csoportok-->

    <csoport csoport_id="1" produkcio="1">
        <tagok_szama>15</tagok_szama>
        <nev>Arany Csillagok</nev>
        <egyesulet>Táncművészeti Egyesület</egyesulet>
        <korcsoport>25-30</korcsoport>
    </csoport>

    <csoport csoport_id="2" produkcio="2">
        <tagok_szama>10</tagok_szama>
        <nev>Kis Angyalok</nev>
        <egyesulet>Balett Stúdió</egyesulet>
        <korcsoport>12-18</korcsoport>
        <korcsoport>12-14</korcsoport>
    </csoport>

    <csoport csoport_id="3" produkcio="3">
        <tagok_szama>20</tagok_szama>
        <nev>Latin Ritmusok</nev>
        <egyesulet>Tánciskola</egyesulet>
        <korcsoport>25-30</korcsoport>
    </csoport>

    <csoport csoport_id="4" produkcio="4">
        <tagok_szama>12</tagok_szama>
        <nev>Jazz Express</nev>
        <egyesulet>Művészeti Társulat</egyesulet>
        <korcsoport>18-22</korcsoport>
    </csoport>

    <csoport csoport_id="5" produkcio="5">
        <tagok_szama>18</tagok_szama>
        <nev>Flamenco Szenvedély</nev>
        <egyesulet>Táncműhely</egyesulet>
        <korcsoport>25-30</korcsoport>
    </csoport>    

    <!--Versenyzők-->

    <versenyzo versenyzo_id="1" tag="1">
        <eletkor>25</eletkor>
        <nev>Kovács Anna</nev>
        <szuletesi_datum>1998-04-10</szuletesi_datum>
        <lakcim>
            <iranyitoszam>1024</iranyitoszam>
            <varos>Budapest</varos>
            <utca_hazszam>Kossuth utca 10</utca_hazszam>
        </lakcim>
    </versenyzo>

    <versenyzo versenyzo_id="2" tag="3">
        <eletkor>30</eletkor>
        <nev>Szabó Bence</nev>
        <szuletesi_datum>1992-08-22</szuletesi_datum>
        <lakcim>
            <iranyitoszam>1132</iranyitoszam>
            <varos>Budapest</varos>
            <utca_hazszam>Rákospatak utca 5</utca_hazszam>
        </lakcim>
    </versenyzo>

    <versenyzo versenyzo_id="3" tag="4">
        <eletkor>22</eletkor>
        <nev>Molnár Rita</nev>
        <szuletesi_datum>2001-05-28</szuletesi_datum>
        <lakcim>
            <iranyitoszam>3521</iranyitoszam>
            <varos>Debrecen</varos>
            <utca_hazszam>Sport utca 8</utca_hazszam>
        </lakcim>
    </versenyzo>

    <versenyzo versenyzo_id="4" tag="1">
        <eletkor>28</eletkor>
        <nev>Nagy Ferenc</nev>
        <szuletesi_datum>1995-11-15</szuletesi_datum>
        <lakcim>
            <iranyitoszam>4023</iranyitoszam>
            <varos>Debrecen</varos>
            <utca_hazszam>Sport tér 15</utca_hazszam>
        </lakcim>
    </versenyzo>

    <versenyzo versenyzo_id="5" tag="4">
        <eletkor>19</eletkor>
        <nev>Kiss Mária</nev>
        <szuletesi_datum>2004-07-03</szuletesi_datum>
        <lakcim>
            <iranyitoszam>1015</iranyitoszam>
            <varos>Budapest</varos>
            <utca_hazszam>Sport út 20</utca_hazszam>
        </lakcim>
    </versenyzo>

    <versenyzo versenyzo_id="6" tag="2">
        <eletkor>14</eletkor>
        <nev>Nagy Éva</nev>
        <szuletesi_datum>2009-09-05</szuletesi_datum>
        <lakcim>
            <iranyitoszam>4400</iranyitoszam>
            <varos>Nyíregyháza</varos>
            <utca_hazszam>Kossuth tér 5</utca_hazszam>
        </lakcim>
    </versenyzo>
    
    <versenyzo versenyzo_id="7" tag="3">
        <eletkor>26</eletkor>
        <nev>Kovács Péter</nev>
        <szuletesi_datum>1997-12-18</szuletesi_datum>
        <lakcim>
            <iranyitoszam>3525</iranyitoszam>
            <varos>Debrecen</varos>
            <utca_hazszam>Kisfaludy utca 12</utca_hazszam>
        </lakcim>
    </versenyzo>

    <versenyzo versenyzo_id="8" tag="3">
        <eletkor>29</eletkor>
        <nev>Szabó József</nev>
        <szuletesi_datum>1993-06-30</szuletesi_datum>
        <lakcim>
            <iranyitoszam>1139</iranyitoszam>
            <varos>Budapest</varos>
            <utca_hazszam>Kiss János utca 8</utca_hazszam>
        </lakcim>
    </versenyzo>

    <versenyzo versenyzo_id="9" tag="2">
        <nev>Szűcs László</nev>
        <szuletesi_datum>2010-02-14</szuletesi_datum>
        <lakcim>
            <iranyitoszam>4405</iranyitoszam>
            <varos>Nyíregyháza</varos>
            <utca_hazszam>Petőfi tér 3</utca_hazszam>
        </lakcim>
    </versenyzo>

    <versenyzo versenyzo_id="10" tag="2">
        <nev>Balogh Judit</nev>
        <szuletesi_datum>2008-11-10</szuletesi_datum>
        <lakcim>
            <iranyitoszam>3522</iranyitoszam>
            <varos>Debrecen</varos>
            <utca_hazszam>Bajnai út 7</utca_hazszam>
        </lakcim>
    </versenyzo>    

    <!--A tánc helye több-több kapcsolat-->

    <tanc_helye th_id="1" tanc_id="1" verseny_id="1">
        <pontszam>78</pontszam>
    </tanc_helye>

    <tanc_helye th_id="2" tanc_id="2" verseny_id="1">
        <pontszam>86</pontszam>
    </tanc_helye>

    <tanc_helye th_id="3" tanc_id="3" verseny_id="5">
        <pontszam>58</pontszam>
    </tanc_helye>

    <tanc_helye th_id="4" tanc_id="4" verseny_id="3">
        <pontszam>37</pontszam>
    </tanc_helye>

    <tanc_helye th_id="5" tanc_id="5" verseny_id="2">
        <pontszam>64</pontszam>
    </tanc_helye>

    <tanc_helye th_id="6" tanc_id="1" verseny_id="4">
        <pontszam>75</pontszam>
    </tanc_helye>

    <tanc_helye th_id="7" tanc_id="3" verseny_id="1">
        <pontszam>46</pontszam>
    </tanc_helye>

    <tanc_helye th_id="8" tanc_id="5" verseny_id="3">
        <pontszam>86</pontszam>
    </tanc_helye>

    <tanc_helye th_id="9" tanc_id="2" verseny_id="2">
        <pontszam>57</pontszam>
    </tanc_helye>

    <tanc_helye th_id="10" tanc_id="4" verseny_id="1">
        <pontszam>87</pontszam>
    </tanc_helye>

    <!--Lejátszott zene több-több kapcsolat-->

    <lejatszott_zene tanc_id="1" zene_id="4"/>
    <lejatszott_zene tanc_id="2" zene_id="3"/>
    <lejatszott_zene tanc_id="4" zene_id="2"/>
    <lejatszott_zene tanc_id="5" zene_id="5"/>
    <lejatszott_zene tanc_id="3" zene_id="1"/>

</F4IIYA_Tancverseny>
